import { DynamoDBClient, UpdateItemCommand } from "@aws-sdk/client-dynamodb";

const ddb = new DynamoDBClient({});
const TABLE_NAME = process.env.TABLE_NAME!;
const WHATSAPP_ACCESS_TOKEN = process.env.WHATSAPP_ACCESS_TOKEN!;
const WHATSAPP_PHONE_ID = process.env.WHATSAPP_PHONE_ID!; 

export const handler = async (event: any) => {
  console.log(`Processing batch of ${event.Records.length} messages from SQS`);
  
  const batchItemFailures: { itemIdentifier: string }[] = [];

  for (const record of event.Records) {
    const messageId = record.messageId;
    let payload;

    try {
      payload = JSON.parse(record.body);
      const { pk, sk, recipientPhone, templateName } = payload;

      if (!pk || !sk || !recipientPhone) {
        throw new Error(`Missing required fields in payload for sk: ${sk}`);
      }

      // 1. Dispatch the template message to Meta Graph API
      const metaUrl = `https://graph.facebook.com/v20.0/${WHATSAPP_PHONE_ID}/messages`;
      
      const metaResponse = await fetch(metaUrl, {
        method: "POST",
        headers: {
          "Authorization": `Bearer ${WHATSAPP_ACCESS_TOKEN}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          messaging_product: "whatsapp",
          recipient_type: "individual",
          to: recipientPhone,
          type: "template",
          template: {
            name: templateName,
            language: { code: "en_US" } // Adjust or pull dynamically from payload if needed
          }
        }),
      });

      const metaData = await metaResponse.json();

      if (!metaResponse.ok) {
        console.error("Meta API Error:", JSON.stringify(metaData));
        throw new Error(`Meta API rejected request for ${recipientPhone}: ${metaData.error?.message}`);
      }

      // Extract the WhatsApp Message ID (wamid) generated by Meta
      const wamid = metaData.messages?.[0]?.id;
      if (!wamid) {
        throw new Error("Meta API succeeded but no wamid was returned.");
      }

      console.log(`Successfully dispatched to ${recipientPhone}. WAMID: ${wamid}`);

      // 2. Map the WAMID back to the recipient in DynamoDB
      // This step is critical—it populates the gsi1pk so inbound delivery webhooks can find this record!
      await ddb.send(
        new UpdateItemCommand({
          TableName: TABLE_NAME,
          Key: {
            pk: { S: pk },
            sk: { S: sk },
          },
          UpdateExpression: "SET whatsappMessageId = :wamid, gsi1pk = :gsi1pk, deliveryStatus = :status, updatedAt = :now",
          ExpressionAttributeValues: {
            ":wamid": { S: wamid },
            ":gsi1pk": { S: `MSG#${wamid}` }, // Maps to your webhook index
            ":status": { S: "SENT" },
            ":now": { S: new Date().toISOString() },
          },
        })
      );
      
    } catch (error: any) {
      console.error(`Failed to process SQS record ${messageId}:`, error.message);
      // Pushing the ID here tells SQS to keep this specific message in the queue and retry it later, 
      // while allowing the rest of the batch to be deleted successfully.
      batchItemFailures.push({ itemIdentifier: messageId });
    }
  }

  return { batchItemFailures };
};